### ISSUE TITLE
QGIS Crashes every time "Selected layer" is selected as input polyline

### ISSUE THREAD

**Issue by mudomau** [PANOimagen/profiletool#40] opened 2020-03-04 15:35 UTC
Using QGIS v3.10.2 LTR, Windows 10.

Profile tool works OK when using the temporary polyline tool, but if I try to use an existing layer the program freezes and crashes.

**Comment by JaviBecerra** [comment] 2020-03-04 15:50
Hi,
This seems like a duplicate of issue #35, which was solved by ProfileTool plugin version 4.1.8.
You may have to update the plugin from QGIS manager to the latest version.
I am marking the issue as duplicate and closing it; feel free to reopen it if updating the plugin to the latest version does not work for you (you can check installed version on Plugins->Profile Tool->About).

**Closed by JaviBecerra** 2020-03-04 15:50 UTC
Labels: duplicate
