### ISSUE TITLE
Profiletool crashes Qgis on install

### ISSUE THREAD

**Issue by palousegeo** [PANOimagen/profiletool#23] opened 2019-03-14 22:19 UTC
I tried to install the profile tool plugin and it crashed QGIS. This happened on two different computers both Windows 10 with versions 3.4.5, 3.6.0 and 3.7.0. The tool does show up in the plugins list after the crash. However, it crashes the program again when I try to activate it. I also tried a fresh profile with the profile tool as the only added plugin and it also crashed QGIS.
[profiletool_crash.txt](https://github.com/PANOimagen/profiletool/files/2968698/profiletool_crash.txt)

**Comment by JaviBecerra** [comment] 2019-03-15 07:39
Hi @palousegeo,
We have tested the plugin on windows 8.1 against QGis 3.4.4 and 3.6.0, and on windows 10 against 3.4.3 without an issue. We are checking again on Windows 10 against newer versions just in case something changed in 3.4.5.

Looking at the stack trace we are finding a PyErr_NoMemory, could it be an issue with your system's available RAM? Are you trying to install the plugin while loading some big layers on memory?

Can you see any error messages on the Python message pane? Perhaps that could help us find out a bit more.

**Comment by palousegeo** [comment] 2019-03-15 20:32
Hi,
The plugin appears to install properly, but instantly crashes QGIS upon activation (checking the box in the plugin manager). The main computer I am testing this on has 16 GB ram. I monitored memory usage while trying to activate the plugin. The usage stayed steady around 4 GB. I tried to activate the plugin on a fresh profile with the rest of the standard plugins disabled. QGIS still crashed. Unfortunately, it happens so fast there is no python error reported.

I also tried to install the plugin on a third computer, a MS Surface Pro 3, with a quad core i7 processor and 8 GB of RAM running Windows 10 pro. Same result – instant QGIS crash upon plugin activation. If I can provide any additional information that will help you please let me know.
-Rick

________________________________

**Comment by JaviBecerra** [comment] 2019-03-18 08:18
Hi Rick,
We have checked with another windows 10 machine with 3.4.4 and 3.6.0 and we have not been able to reproduce the issue yet :(
Can you please provide the following info:
-What version of the plugin are you using, the latest one available from the QGis plugin repository or you installed manually the one in github (we have to publish an update with latests commits so they are slightly out of sync). If you have been using the plugin manager to download the plugin, please try installing manually the latest version on github.
-Have you used the QGis standalone installer or the OSGeo installer for the QGis installation?
-Have you had any issue with any other plugin or is this issue exclusive to ProfileTool?
-Can you think of any tool/plugin/loaded layer... shared by the different setups you tested?

The stack trace does not seem to show any call to the plugin's code itself, but I am not too familiar with QGis/Qt plugin loading system. We will send an email to qgis-dev list if we are not able to find out what is causing this and see if someone has a better idea of what is going on according to that stacktrace.

**Comment by JaviBecerra** [comment] 2019-03-18 09:03
I have found some bug reports with quite similar stacktraces:

https://issues.qgis.org/issues/18220
https://issues.qgis.org/issues/19197
https://github.com/bstroebl/DigitizingTools/issues/30

However all of them seem to be solved by reinstalling QGis, the plugins or both...

**Comment by JaviBecerra** [comment] 2019-04-03 06:39
Hi @palousegeo:
Any news on this issue? Have you finally been able to install the plugin?
If you still have trouble, can you please provide us with the information I mentioned in my previous comment (https://github.com/PANOimagen/profiletool/issues/23#issuecomment-473811625)
Regards,
Javier

**Comment by palousegeo** [comment] 2019-04-11 22:52
Sorry, I haven't had much time available for testing. However, I updated both QGIS (3.6.1) and the profile tool (4.1.6) today. As soon as I activated the tool QGIS crashed. This is the case for a diverse set of 4  Windows 10 computers I usually work on. On each of these computers I installed and updated QGIS through the OSGEO4Wx64 packages. I am not having issues with other plugins. As mentioned above, I tried this on a clean profile (no plugins other than the base set, with all these turned off) with the same results.

**Comment by JaviBecerra** [comment] 2019-04-12 12:07
Hi @palousegeo, no worries.

We have tried reinstalling QGis with the OSGEO4Wx64 "Express Desktop" install and we still can not reproduce the issue. Are you using any particular options during install?
Could you try with the QGis standalone installer?

**Comment by palousegeo** [comment] 2019-04-17 19:38
Hi,
I finally have something useful to report. All of my QGIS installs used the OSGEO4Wx64 “Advanced” package. I had added many of the additional libraries available through that installation option. I uninstalled the OSGEO4W package and replaced it with the “Express” version. This kept my existing plugins, but deleted the extra libraries. Under this scenario the Profile tool runs as expected. Unfortunately, I can’t point to what the conflict is since there are too many options with the “Advanced” package.

**Comment by JaviBecerra** [comment] 2019-04-29 07:01
Thanks @palousegeo, that explains why we are not able to reproduce it.
If you can provide us with a list of the options that you modify with regards to the default configuration options in advanced mode we can give it a try to find out the culprit, but this will surely take us some time.

**Comment by Aewaterhouse** [comment] 2019-05-09 06:34
Hi, 
I was also experiencing the same issues as described by @palousegeo, and have also managed to resolve it by changing the Osgeo4W setup from "Advanced" mode to the "Express Desktop" mode. 
To reproduce my issue, I was previously selecting all the packages for installation.
Regards,
Alex

**Comment by JaviBecerra** [comment] 2019-05-09 08:22
Thanks to @Aewaterhouse report we have been able to reproduce the issue on one of our machines, selecting all packages during installation.
We have isolated the offending call somewhere down to this import on profileplugin.py:
```python
from .tools.profiletool_core import ProfileToolCore
```
Moving it to line 90 (i.e. importing class ProfileToolCore right before using it), the crash is delayed until we try to open the plugin window, but there are no more problems during installation of the plugin or when opening QGis.

However ```profiletool_core.py``` is a rather complex module, not sure where the problem comes from yet. We'll keep on digging...

**Comment by dd-a** [comment] 2019-05-09 08:56
I have the same crash on a Mac (Mac OS 10.13.6 ) with QGis 3.4.7 and 3.6.2 from Homebrew/Lutraconsulting.  However iIt does not crash with QGis 3.4.7 from Kyngchaos (QGis official distribution).  Here are the differences I see 

_Kyngchaos (compatible with Profile Tool)_ 
- Version de QGIS | 3.4.7-Madeira |
- Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
- Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
- Compilé avec GEOS | 3.7.1-CAPI-1.11.0 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
- Version du client PostgreSQL | 9.6.10 | Version de SpatiaLite | 4.4.0-RC1
- Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
- Compilé avec PROJ | 520 | Fonctionne avec PROJ | 5.2.0

_Homebrew (NOT compatible with Profile Tool)_
Version de QGIS | 3.4.7-Madeira | Révision du code | 5c56989325
Compilé avec Qt | 5.12.2 | Utilisant Qt | 5.12.2
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.1-CAPI-1.11.1 | Utilisé avec GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Version du client PostgreSQL | 11.2 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 600 | Fonctionne avec PROJ | 6.0.0

HTH

**Comment by JaviBecerra** [comment] 2019-05-09 11:18
Hi,
I think that we have finally pinned down the source of crashes. 
Thanks to another crash report with a similar trace (see NeurodataWithoutBorders/api-python#28) we could link PyInit__conv to an hdf5 related library, which profiletool does not need but is anyway imported by the copy of pyqtgraph bundled with the plugin. 
Many libraries incorporate hdf5 support, and it would seem that there may be some conflicts when they are compiled against or even bundling different dll versions (when using Os4Geo 'install all packages' option I find at least 12 hdf5 related dlls, including 3 different copies with different sizes of hdf5.dll or hdf5_hl.dll).

So, we have removed hdf5 support from the bundled pyqtgraph library on commit https://github.com/PANOimagen/profiletool/commit/6a47bb0c8d5b64a865a5d80a818ffcdac861a74d
This solves the issue on our test machine (though there is still a nasty error message when closing QGis after using profiletool :/ ). 
If @palousegeo and @dd-a can confirm that installing the latest version solves the issue we will close it and publish the updated version to QGis repos.

**Comment by dd-a** [comment] 2019-05-09 11:33
No more crashes, tested with QGis 3.4.7 and 3.6.2 .   Thank you very much !

**Comment by JaviBecerra** [comment] 2019-05-10 07:20
Cool @dd-a, you are welcome!
Thanks @palousegeo, @Aewaterhouse and @dd-a for your help!
I am closing the issue now, we will be publishing an updated version to QGis repos next week to solve this.
Feel free to reopen it you find this stacktrace again (or a similar one with a PyInit__conv call on the first line of the trace).
Regards

**Closed by JaviBecerra** 2019-05-10 07:20 UTC
Labels: bug
