### ISSUE TITLE
Problem with selected polyline

### ISSUE THREAD

**Issue by smorant89** [PANOimagen/profiletool#37] opened 2019-11-13 17:09 UTC
I have been using profile tool with QGIS 2.18 version without problems, i could use all the functions it has. But surprisely when I updated to the 3.10 I only be able to use the temporary Line, cause when I select the option "selected polyline" ,after select the lline vector layer I want, and the selection hand appears and I select the line which I want to determine the profile,  my computer crash and freeze. 

What I have to do? What will be the problem and solution?

**Comment by JaviBecerra** [comment] 2019-11-15 12:49
Hi @smorant89,
This seems a duplicate of issue #35 (although there are no reports of QGIS crashing over there). 
I am marking this as duplicate and closing it now, I will reopen it if it turns out to be a different issue.
Thanks for taking the time to report it!

**Closed by JaviBecerra** 2019-11-15 12:50 UTC
Labels: duplicate
