### ISSUE TITLE
Scaling issue when exporting PyQtGraph profile to SVG

### ISSUE THREAD

**Issue by kevinstadler** [PANOimagen/profiletool#27] opened 2019-05-24 07:21 UTC
When I export a profile as SVG using PyQtGraph, the background grid and labels seem to be rendered using a different scale than the actual profile data, see here (have to upload as zip because Github doesn't support embedding svg graphics): [TLGfull.svg.zip](https://github.com/PANOimagen/profiletool/files/3215552/TLGfull.svg.zip)

PNG export of the same profile looks fine:
![TLGfull](https://user-images.githubusercontent.com/7602414/58309338-8539c400-7e36-11e9-8a43-8fb7a8aae152.png)

(The SVG exported using Matplotlib plotting looks fine regarding scale, but the axis labels are cut off.)

**Comment by JaviBecerra** [comment] 2019-05-24 08:59
Hi @kevinstadler,
Thanks for reporting the issue. 
We have reproduced your issue on Windows 8.1 using QGis 3.4.4 64 bits, by changing the size of system fonts to the biggest allowed size. Could it be that you are using a high density screen (anything greater than fullHD) and/or use a big size for system fonts?

If so, as a temporal workaround you can change the size of system fonts to a small size when exporting.

Matplotlib backend seems to be working fine, could you upload a sample where labels cut off? Please also report on the version of QGis and operating system that you are using.
Regards

**Comment by kevinstadler** [comment] 2019-05-25 00:58
Hello,
I'm on MacOS High Sierra 10.13.6, using the QGIS 3.6.3 build installed from osgeo4mac Homebrew: https://github.com/OSGeo/homebrew-osgeo4mac
I'm on a relatively old Macbook Air (screen resolution 1440x900) with all default font settings.

I just realised that the matplotlib plot labels are already cut off in the Profile Tool panel itself, because the screen area is simply too small to get them on, and the export (to any format) only exports what's visible in the panel obviously. I managed to avoid cutting off the x-axis labels by increasing the height of the panel, but my screen simply isn't wide enough to stop the y-axis labels from being cut off, even if I head the right-hand side "select layer/line" part of the plugin. Instead of the exported image here's a screenshot of the situation:
![Screen Shot 2019-05-25 at 08 54 46](https://user-images.githubusercontent.com/7602414/58362560-d1364880-7eca-11e9-879c-d8e9238bd606.png)
I don't know how cumbersome this would be to implement with any of the plotting plugins, but an option to select the axis label font size would be a great feature.

**Comment by JaviBecerra** [comment] 2019-05-28 08:12
Thanks for the info @kevinstadler !
I have uploaded a commit fixing the exporting issues for matplotlib backend, now all the formats should be ok, please check that it is working fine for you.
I will take a look at pyqtgraph and the matplotlib visualization issues asap, but in the meantime you can just use matplotlib backend to export your figures.
Regards

**Comment by ChameleonScales** [comment] 2019-09-10 10:58
I had the same issue but after updating the plugin it worked fine (Debian 9, QGIS 3.4). Thanks for the fix!

**Comment by nicogodet** [comment] 2021-09-03 20:48
seems fixed on my side too.

**Closed by nicogodet** 2021-09-03 20:48 UTC
Labels: bug
